export const SAVE_USER = "SAVE_USER";

export const SET_SELECTED_CHAT = "SET_SELECTED_CHAT";
export const RESET_SELECTED_CHAT = "RESET_SELECTED_CHAT";

export const SET_SINGLE_CHAT = "SET_SINGLE_CHAT";

export const SET_ROOM_STATUS = "SET_ROOM_STATUS";
